---
title: "Notebook for Analysis Plan exploring relationship between obesity and life expectancy"
output: html_notebook
author: 
- Jon Minton
- Rebecca Devine
---

# Obesity Analysis Plan – Part 1 – international comparison of obesity and life expectancy

## RQ1: 

`Are the countries which saw the largest increases in obesity prevalence the same which had slowing of life expectancy?`

## Setting:

36 OECD countries: 

* Australia, 
* Austria,
* Belgium, 
* Canada, 
* Chile, 
* Czech Republic, 
* Denmark, 
* Estonia, 
* Finland, 
* France, 
* Germany, 
* Greece, 
* Hungary, 
* Iceland, 
* Ireland, 
* Israel, 
* Italy, 
* Japan, 
* South Korea, 
* Latvia, 
* Lithuania, 
* Luxembourg, 
* Mexico, 
* Netherlands, 
* New Zealand, 
* Norway, 
* Poland, 
* Portugal, 
* Slovak Republic, 
* Slovenia, 
* Spain, 
* Sweden, 
* Switzerland, 
* Turkey, 
* Scotland, 
* England, 
* Northern Ireland, 
* Wales, 
* United States.   

## Exposure:

* Obesity (BMI 30+)

## Measure of exposure:

* Change in (age standardised) proportion of adult population (age 20+) defined as obese (BMI 30+) between 1980 and 2015.

## Outcome:

* Life Expectancy

## Measure of outcome: 

* Change in life expectancy at birth (years), for males and females, between 1980-1985 and 2015-2020.

## Output: 

* Scatter plot, with proportion of population obese (BMI 30+) on x-axis and average life expectancy at birth on y-axis, by country

## Data Sources:

### Obesity

* NB no collated source of national survey data identified.  
* [This GBD paper](http://www.healthdata.org/research-article/health-effects-overweight-and-obesity-195-countries-over-25-years) published relevant data on obesity, systematically gathered from Medline and Global Health Data Exchange.
* See in particular: [Table S3](https://www.nejm.org/doi/suppl/10.1056/NEJMoa1614362/suppl_file/nejmoa1614362_appendix.pdf). The age‐standardized prevalence of overweight and obesity among children and adults by sex in 1980 and 2015 among 195 countries. page 33 of the supplementary appendix.  

### Life expectancy

* **Source**: World Population Prospects: The 2019 Revision, United Nations Population Division
    * http://data.un.org/Data.aspx?q=life+expectancy&d=PopDiv&f=variableID%3a66
    * http://data.un.org/Data.aspx?q=life+expectancy&d=PopDiv&f=variableID%3a67


# Research

## Research Stages 

The stages required: 

* Data prep
  * Load Obesity Data
  * Sense check the data
  * Find subset of the 36 OECD countries listed, age 20+ 
  * Load life expectancy data
  * Sense check the data 
  * Find subset of 36 OECD data 
  * Join the data
* Analysis 
  * Scatterplots by year
  * Regression coefficients 
  
## Data Preparation 

### Obesity Data 

#### Data Loading 



